

# input and output files
input_file: 'test/input.xlsx'
output_file: 'out.xlsx'
number_of_cameras: 9 # number of physical cameras, aka measure points 

# all possible parameters to Počty vozidel sheet
# all day (aka 00:00 -> 23:59) is created by default
sheet_cars_count: 
  time_a:
    time_start: '04:50' #inclusive, time format is HH:MM
    time_end: '04:50' #inclusive

  # Or you can specify start and end date. Like in example below. 
  time_b: # for more times just add new 'time_x' section
    dateTime_start: '6.10.2021 - 00:01' # inclusive, dateTime format is ~dd.mm.YYYY - HH:MM~ 
    dateTime_end: '6.10.2021 - 23:59' # inclusive
  
# there are no parameters for Počty průjezdů sheet

# all possible parameters to Časové údaje sheet
sheet_times: 
  time_a: 
    selected_directions: # full indexing format, aka index 6 corresponds to camera 3 looking backwards
      - 1
      - 3
      - 10
      - 12
    time_start: '00:00'
    time_end: '23:59'

  # Or you can specify start and end date. Like in example below. 
  time_b: # for more times just add new 'time_x' section
    selected_directions: 
      - 1
      - 12
    dateTime_start: '6.10.2021 - 00:01' # inclusive, dateTime format is ~dd.mm.YYYY - HH:MM~ 
    dateTime_end: '7.10.2021 - 18:00' # inclusive


  