
###################### PARAMETERS ######################
## add or update to change behavior of script         ##
########################################################

################## DATETIME CONVENTIONS ################
## both start and end dateTime must have this format  ##
## dd.mm.YYYY - HH:MM, f.e: 6.10.2021 - 23:59         ##
## both times (start and end) are inclusive           ##
########################################################

################# INPUT AND OUTPUT FILES ###############
input_file: 'test/input_with_categories.xlsx'
output_file: 'out2.xlsx'
number_of_cameras: 9 # number of physical cameras, aka measure points 

################# SHEET POČTY VOZIDEL ###############
# all day (aka 00:00 -> 23:59) is created by default
sheet_cars_count: 
  output_a:
    dateTime_start: '19.9.2023 - 00:00'
    dateTime_end: '19.9.2023 - 23:59'

    # keep only rows, whose `Kategorie` value is any of following
    selected_categories: ['OA', 'BUS', 'LN', 'TN']

  # for more different outputs (with different times or category selectors) just add new 'output_x' section
  output_b:
    dateTime_start: '19.9.2023 - 4:50'
    dateTime_end: '19.9.2023 - 10:00'

    # when `selected_categories` is omitted or empty, all categories are selected
    selected_categories: []

  output_c:
    dateTime_start: '19.9.2023 - 00:00'
    dateTime_end: '19.9.2023 - 23:59'

    # keep only rows, whose `Kategorie` value is any of following
    selected_categories: ['LN', 'TN']


################# SHEET POČTY PRŮJEZDŮ ###############
# all day (aka 00:00 -> 23:59) is created by default
sheet_number_of_travels:
  output_a:
    dateTime_start: '7.10.2021 - 04:50' 
    dateTime_end: '7.10.2021 - 20:21' 

  # for more different outputs (with different times or category selectors) just add new 'output_x' section
  output_b:
    dateTime_start: '7.10.2021 - 04:50' 
    dateTime_end: '7.10.2021 - 20:21' 


################## SHEET ČASOVÉ ÚDAJE #################
sheet_times: 
  output_a:
    selected_directions: # full indexing format, aka index 6 corresponds to camera 3 looking backwards
      - 1
      - 3
    dateTime_start: '2.11.2021 - 00:00'
    dateTime_end: '4.11.2021 - 23:59'

  # for more different outputs (with different times, selected directions or category selectors) just add new 'output_x' section
  output_b:
    selected_directions: 
      - 1
      - 12
    dateTime_start: '6.10.2021 - 00:01'
    dateTime_end: '7.10.2021 - 18:00'


  